//  FICHERO AUTOGENERADO - NO MODIFICAR
//  StoryboardConstants.h
//
//  Created by SDOS
//

#import <Foundation/Foundation.h>

extern NSString * const SBNameExampleSDOSHero;

extern NSString * const SBNameLaunchScreen;

 //
 // ExampleSDOSHero.h
 // Generated by seguecode

#pragma once

#import <UIKit/UIKit.h>

@interface UINavigationController (ExampleSDOSHero)

@end
#import "SDOSHeroViewController.h"

@interface SDOSHeroViewController (ExampleSDOSHero)
- (IBAction)segueShowDetailStoryboardSegueFrom;
- (void)segueShowDetailStoryboardSegueFromWithInfo:(id)info;

@end
#import "SDOSHeroNavigationController.h"

@interface SDOSHeroNavigationController (ExampleSDOSHero)

@end
#import "InitialViewController.h"

@interface InitialViewController (ExampleSDOSHero)

@end
#import "SDOSHeroDetailViewController.h"

@interface SDOSHeroDetailViewController (ExampleSDOSHero)

@end

 //
 // LaunchScreen.h
 // Generated by seguecode

#pragma once

#import <UIKit/UIKit.h>

@interface UIViewController (LaunchScreen)

@end

// Auto generated file - any changes will be lost

#import <Foundation/Foundation.h>

#pragma mark - navigationController.storyboardIdentifier
extern NSString * const SDOSHeroDetailNavigationViewControllerIdentifier;
extern NSString * const SDOSHeroNavigationControllerIdentifier;

#pragma mark - segue.identifier
extern NSString * const ShowDetailStoryboardSegue;

#pragma mark - storyboardNames
extern NSString * const ExampleSDOSHero;
extern NSString * const LaunchScreen;

#pragma mark - viewController.storyboardIdentifier
extern NSString * const SDOSHeroDetailViewControllerIdentifier;


