//  FICHERO AUTOGENERADO - NO MODIFICAR
//  StoryboardConstants.m
//
//  Created by SDOS
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

NSString * const SBNameExampleSDOSHero = @"ExampleSDOSHero";

NSString * const SBNameLaunchScreen = @"LaunchScreen";

 //
 // ExampleSDOSHero.m
 // Generated by seguecode


NSString * const FromShowDetailStoryboardSegueToSDOSHeroDetailViewControllerIdentifier = @"ShowDetailStoryboardSegue";

@implementation UINavigationController (ExampleSDOSHero)

@end
@implementation SDOSHeroViewController (ExampleSDOSHero)
- (IBAction)segueShowDetailStoryboardSegueFrom
{
    [self segueShowDetailStoryboardSegueFromWithInfo:nil];
}

- (void)segueShowDetailStoryboardSegueFromWithInfo:(id)info
{
     [self performSegueWithIdentifier:FromShowDetailStoryboardSegueToSDOSHeroDetailViewControllerIdentifier sender:info];
}

@end
@implementation SDOSHeroNavigationController (ExampleSDOSHero)

@end
@implementation InitialViewController (ExampleSDOSHero)

@end
@implementation SDOSHeroDetailViewController (ExampleSDOSHero)

@end

 //
 // LaunchScreen.m
 // Generated by seguecode


@implementation UIViewController (LaunchScreen)

@end

// Auto generated file - any changes will be lost


#pragma mark - navigationController.storyboardIdentifier
NSString * const SDOSHeroDetailNavigationViewControllerIdentifier = @"SDOSHeroDetailNavigationViewControllerIdentifier";
NSString * const SDOSHeroNavigationControllerIdentifier = @"SDOSHeroNavigationControllerIdentifier";

#pragma mark - segue.identifier
NSString * const ShowDetailStoryboardSegue = @"ShowDetailStoryboardSegue";

#pragma mark - storyboardNames
NSString * const ExampleSDOSHero = @"ExampleSDOSHero";
NSString * const LaunchScreen = @"LaunchScreen";

#pragma mark - viewController.storyboardIdentifier
NSString * const SDOSHeroDetailViewControllerIdentifier = @"SDOSHeroDetailViewControllerIdentifier";


