source 'https://github.com/SDOSLabs/cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_modular_headers!
inhibit_all_warnings!

def shared_pods
	pod 'SDOSHero', :path => '../../'
end

target :SDOSHeroExample do
	shared_pods
end
